# Generated by Django 5.0.7 on 2025-12-12 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('Taboo', 'Taboo'), ('System', 'System')], default='C', max_length=10)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=10)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('intel_depth', models.FloatField(default=0.0)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAnniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversaries', to='intelligence.target')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EVENT', 'Event'), ('ANSWER', 'Answer')], default='EVENT', max_length=10)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('Alert', 'Alert')], default='Neutral', max_length=10)),
                ('related_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.quest')),
                ('tags', models.ManyToManyField(blank=True, to='intelligence.tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='intelligence.target')),
            ],
        ),
    ]
