# Generated by Django 5.0.7 on 2025-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='memo',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='target',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='target',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='target',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='target',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='last_name',
        ),
        migrations.AddField(
            model_name='target',
            name='aliases',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='target',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
