# Generated by Django 5.0.7 on 2025-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_rename_memo_target_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='rank',
        ),
        migrations.AddField(
            model_name='target',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='zodiac_sign',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
