# Generated by Django 5.0.7 on 2025-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_remove_target_name_remove_target_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='target',
            old_name='origin',
            new_name='birthplace',
        ),
        migrations.RemoveField(
            model_name='target',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='target',
            name='height',
        ),
        migrations.RemoveField(
            model_name='target',
            name='weight',
        ),
        migrations.AddField(
            model_name='target',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A型'), ('B', 'B型'), ('O', 'O型'), ('AB', 'AB型'), ('Unknown', '不明')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Other', 'その他'), ('Unknown', '不明')], default='Female', max_length=10),
        ),
        migrations.AddField(
            model_name='target',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='targets', to='intelligence.targetgroup'),
        ),
    ]
