# Generated by Django 5.0.7 on 2025-12-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_quest_user_targetgroup_user_alter_targetgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgroup',
            name='is_fri',
            field=models.BooleanField(default=False, verbose_name='金'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='is_mon',
            field=models.BooleanField(default=False, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='is_sat',
            field=models.BooleanField(default=False, verbose_name='土'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='is_sun',
            field=models.BooleanField(default=False, verbose_name='日'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='is_thu',
            field=models.BooleanField(default=False, verbose_name='木'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='is_tue',
            field=models.BooleanField(default=False, verbose_name='火'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='is_wed',
            field=models.BooleanField(default=False, verbose_name='水'),
        ),
    ]
