# Generated by Django 5.0.7 on 2025-12-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_targetgroup_is_fri_targetgroup_is_mon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='contact_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='question_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='question_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='question_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
