# Generated by Django 5.0.7 on 2025-12-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0008_questionregistry_timelineitem_contact_made_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='target',
            name='intel_depth',
        ),
        migrations.RemoveField(
            model_name='target',
            name='last_contact',
        ),
        migrations.RemoveField(
            model_name='target',
            name='reference_code',
        ),
        migrations.AddField(
            model_name='target',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='role_rank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='target',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customanniversary',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.target'),
        ),
        migrations.AlterField(
            model_name='target',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=5),
        ),
        migrations.AlterField(
            model_name='target',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='target',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='めい'),
        ),
        migrations.AlterField(
            model_name='target',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', '男性'), ('Female', '女性'), ('Other', 'その他')], max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='groups',
            field=models.ManyToManyField(blank=True, to='intelligence.targetgroup'),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='せい'),
        ),
        migrations.AlterField(
            model_name='target',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], default='Neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.target'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='type',
            field=models.CharField(choices=[('Contact', 'Contact'), ('Quest', 'Quest'), ('Note', 'Note'), ('Event', 'Event'), ('Question', 'Question')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyTargetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_manual_add', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.target')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailytargetstate',
            constraint=models.UniqueConstraint(fields=('target', 'date'), name='unique_target_date_state'),
        ),
    ]
