# Generated by Django 5.0.7 on 2025-12-15 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0010_question_delete_questionregistry_target_last_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('SELECTION', '選択式'), ('TEXT', '自由記述')], default='TEXT', max_length=20, verbose_name='回答形式'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, verbose_name='選択肢 (カンマ区切り)'),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明（意図）'),
        ),
        migrations.AddField(
            model_name='question',
            name='example',
            field=models.TextField(blank=True, verbose_name='質問例'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='質問名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='共通/個別'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='question_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='question_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='question_text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.questioncategory'),
        ),
        migrations.CreateModel(
            name='QuestionRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.questionrank'),
        ),
    ]
