# Generated by Django 5.0.7 on 2025-12-16 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0011_remove_question_content_question_answer_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineitem',
            name='related_quest',
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='共通'),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='type',
            field=models.CharField(choices=[('Contact', 'Contact'), ('Note', 'Note'), ('Event', 'Event'), ('Question', 'Question')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
