# Generated by Django 5.0.7 on 2025-12-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0012_remove_timelineitem_related_quest_tag_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='timeline_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='intelligence.timelineitem')),
            ],
        ),
    ]
