# Generated by Django 5.0.7 on 2025-12-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0013_timelineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
